[tool.black]
line-length = 100
target-version = ['py36']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[tool.isort]
known_third_party = [
  "PIL",
  "numpy",
  "pandas",
  "pl_examples",
  "pytorch_lightning",
  "requests",
  "setuptools",
  "torch",
  "torchvision",
  "tqdm",
  "typer",
  "typing_extensions",
  "typing_inspect",
  "wandb",
]
extra_standard_library = ["dataclasses"]
line_length = 100
profile = "black"
force_sort_within_sections = "True"
